language: node_js
sudo: false
node_js: '4'
branches:
  except:
  - edge
  - releases
  - gh-pages
  - no-tracking-release
addons:
  sauce_connect: true
before_deploy: bash ./ci/build_release.sh
deploy:
- provider: releases
  api_key:
    secure: jBohwrAJwcW3KBo6Vr3T0plp0mR2qjHAwDYqAgWmdrLrIlHbYikJyVtQwGjYJDlrc/1rT2pzfkwKAVuMrzUAzcjOK2VlfTOUf48sdlpfQmYWmP5KVIfLLC+BHVG/tM8OCtbLVuoL5GAmyB/I1KOgPu7B1IEtLsDOf3EY1cFatBVCs6n3JWR+fyJgP0pEGngppjQ+mSSP3ti4yTV0zEp0HAjAZmr3J8sM8JHeCTq9oLrOxL7PUvBcD2LVlJ5rZ3rzbPFKo+Mrm3ZcofxflP04OOonV7T52YsGHgwosShCOIk9NTjOEW1KTaAYBwrIuQtDz8qZosdDgeDv3T3d6PokDIa+42jfY/oquCyegpMGvDsznmRcIphaWioozx9YKWkzjIcVzFrf15gVU9cud2h5GSlcapF4rLaNnDYPiwtA/hyszCDI8KkVVE3xxxiljGX0ngsfjJscc123mA1Tw0MkDIIyxaFNWW2foh+AQOH0TVGts7+2viPbXORTPfXLgO/L5PVMBWOANzueHfx4pV7mjOXBnkqjWqI0qHYLRgZDv1Wfd80eO3QL2DfdwDmtl3NAaXsi2X1JzMtZ8ug+U48CKO31kkIsJY2HrY3N6pR/DZv4QzS6QZCuShpSYbzUJ5m9yCwJZYJb6IknNxh0FTIpEAFNvfMbLCHMEKsmA6PeqT0=
  file:
  - dist.tar.gz
  - dist.zip
  skip_cleanup: true
  on:
    repo: commul/lindat-common
    all_branches: true
    condition: '-n "$TRAVIS_TAG"'
- provider: npm
  email: sedlakmichal@gmail.com
  api_key:
    secure: EpHOw9dFoYggHLQCgNLL04QBEPaHN7jYvpS/laZC1n02lZ+4HMUYhhXtwNF6lwhz0e9W9nEGsk2P8k8xwz0P1i7f5pGVGZG0sN3spevmsmb9jd824o5UV2cLcDrf8QsQn/c8S57Hyi27avqr2weYmnFyLPIaGvH1VzbdbShztJai2KmLeTF596DseNQaHIdjjRzyjr5FKeJqNiGXKzAyNPVTtenMVSEe+51tnVQ+jomGAc/v1iR5JwCY2x9svvdtxpP1ImL5SMA/WHItMptoz33E7+wC2lcCQOXcGad+rsOPFZrA+H4NNiImKvFFC4UfdDz0ajQZCKdrFn+2SbfhJ2dxoewByddut2svDVm2eh108TW/CvwKkNKkkc37uZ7WRLl9k7fOHtq3tg5E72zvGJbKqxaZJPS1TGveyZI9fAuXRwH9aBC5prHoTDpAXHL4os5+0j+2rcUIQGrrQkJXN/pQl6hdqk3L31PpWi6HcrZ4lQzkqI3Bdxr39usgYe8IkSqbjjcIUFjccqKwJysNm4RUDCVGIiDhZ55+Pb02LhQrh/8E2DrR1f6Td/f39oKvdzEHHwuSsrPNWTBklG71iPbm9ED3l030kYoZD9YrIIUguVXPTtNM+42alpoF36aVvZjITpCbDNlzkvfYo7gmWKm7fupfaPow+BAUyOwnD3k=
  on:
    repo: ufal/lindat-common
    all_branches: true
    condition: '-n "$TRAVIS_TAG"'
- provider: script
  script: bash ./ci/push_build.sh
  skip_cleanup: true
  on:
    repo: ufal/lindat-common
    all_branches: true
    condition: '-n "$TRAVIS_TAG" || "$TRAVIS_BRANCH" = "master"'
cache:
  directories:
  - node_modules
  - bower_components
env:
  global:
  - NODE_ENV=travis
  - secure: CGPSzL88zF3exPjS1Gk+sa8GerkwFgTVefSK0WyEaf/kEUNL1U4fW6UOHGI5/BFOXyJK94MCbdjcQKoaKqXj9UjIydAg2D+qLJEEfeXBmGdWOSoKk7Efbp/tHNBTCnrFRLsAM9/ZxsyTogDv9R1S6pQMYxDI13yTJ/bwUhfJ0nWVk7kToxpXv1amQ6oUDnhd3PYpJUy0IQ3KgLRWT7zJYOzSAo3FVt4Yku4OghZcCWJKXjrVemPSVgLJYY7fchDiGjlGPU7fe+N+mPM9cOPztDYQ9eY1yIYjyXJ4hvXtmbavsyTRTA+KxsQtsoXOSi0+oU23qUc7/5NKLlX6SADAG5qXWWyZmyflK1IgdDsGinglNclQQYNOoLzdxTwk/w4AIHtyIyba2sykQDLVHNMooRgUmm0Uq1tr6td5Yv0l5cnAt+op2t4fCIFGOS8IJMuMhtH2L3xcOUlHM/Os182R17RRo8Krq7aYg7b9D/fYh2jmRGGR593Ds1/zFaItAcstsm/Bugf3IpK2ao57xe8hcvObU8Oo7P5/qnrabPZ19Y64PcJGiTn9AYGL3PCffnu2mSm2VPegmtkk5uYSkAKcAhJNleJSX5SIwbeapHb0hC5k8ptgH01YMdbR/njonuuHdX6KSEg309c9xvVKE2uFGHEhQe7CkLW0xiLC2nC7AZ8=
  - secure: EN6ZLob000rVz7exIAPs/O+I672ZJF4fWgj5eImbB1jRGB28QCeb//iduUmlOfOJUwhUsSxqMTkrq2ld0HzRRmeg5tSVy1fTDygR4FVc4GVAud5MYDu0LLaNogt3tAkA2RlFflkcGRhwxsjJ3ZTrbUQWq3b8ARLe2QzeuUE4GU1t65Y42TDLsevXfd4haPzShDo2aBzDXe4KuarH0flR+TdBsL1DrLhNsTWoIAD6EgacR/6y06zcUb7mEFJHgGo24jFoHIYeP3fveIAI/yx0LdPfTeWUs6LqA00fBCPO4hSVLFyLhbnMs7Vt36IuG2Au2whqTscbW9cCsyg6pczgIsrmUYZIj19V3IcaZD4j1N856eYZcJZXA0PuXaEBiqUS7dk/RDojatg6SKGTQbsJILRSxPfuHy2vnmda8G8FzQtXY97llpjdHUanxYnYb+w2ZZutm1eeEjlSrjq1Bjcr16M0twS/7UCA0GhY5EqHj+153kdw4LHI8wApvaw7aUL0cuKPdIBfWfuM0pMegCz4TRkjyvq4LC4hEwyxtWuWnpr0cMipatVA5hksr6vyPQFHfUD22Rui7cJByBMUS7RUkFH6JwFuGksvn/jNznZ96KN1tFgQwTmrjVo3FPrKBuHc3wpF4OEOdeDN/IqpRu6C5yKiB3bbQN7IowLj+0wXZeo=
