language: node_js
sudo: false
node_js: '4'
branches:
  except:
  - edge
  - releases
  - gh-pages
  - no-tracking-release
addons:
  sauce_connect: false
before_deploy: bash ./ci/build_release.sh
deploy:
- provider: releases
  api_key:
    secure: jBohwrAJwcW3KBo6Vr3T0plp0mR2qjHAwDYqAgWmdrLrIlHbYikJyVtQwGjYJDlrc/1rT2pzfkwKAVuMrzUAzcjOK2VlfTOUf48sdlpfQmYWmP5KVIfLLC+BHVG/tM8OCtbLVuoL5GAmyB/I1KOgPu7B1IEtLsDOf3EY1cFatBVCs6n3JWR+fyJgP0pEGngppjQ+mSSP3ti4yTV0zEp0HAjAZmr3J8sM8JHeCTq9oLrOxL7PUvBcD2LVlJ5rZ3rzbPFKo+Mrm3ZcofxflP04OOonV7T52YsGHgwosShCOIk9NTjOEW1KTaAYBwrIuQtDz8qZosdDgeDv3T3d6PokDIa+42jfY/oquCyegpMGvDsznmRcIphaWioozx9YKWkzjIcVzFrf15gVU9cud2h5GSlcapF4rLaNnDYPiwtA/hyszCDI8KkVVE3xxxiljGX0ngsfjJscc123mA1Tw0MkDIIyxaFNWW2foh+AQOH0TVGts7+2viPbXORTPfXLgO/L5PVMBWOANzueHfx4pV7mjOXBnkqjWqI0qHYLRgZDv1Wfd80eO3QL2DfdwDmtl3NAaXsi2X1JzMtZ8ug+U48CKO31kkIsJY2HrY3N6pR/DZv4QzS6QZCuShpSYbzUJ5m9yCwJZYJb6IknNxh0FTIpEAFNvfMbLCHMEKsmA6PeqT0=
  file:
  - dist.tar.gz
  - dist.zip
  skip_cleanup: true
  on:
    repo: commul/lindat-common
    all_branches: true
    condition: '-n "$TRAVIS_TAG"'
- provider: npm
  email: sedlakmichal@gmail.com
  api_key:
    secure: EpHOw9dFoYggHLQCgNLL04QBEPaHN7jYvpS/laZC1n02lZ+4HMUYhhXtwNF6lwhz0e9W9nEGsk2P8k8xwz0P1i7f5pGVGZG0sN3spevmsmb9jd824o5UV2cLcDrf8QsQn/c8S57Hyi27avqr2weYmnFyLPIaGvH1VzbdbShztJai2KmLeTF596DseNQaHIdjjRzyjr5FKeJqNiGXKzAyNPVTtenMVSEe+51tnVQ+jomGAc/v1iR5JwCY2x9svvdtxpP1ImL5SMA/WHItMptoz33E7+wC2lcCQOXcGad+rsOPFZrA+H4NNiImKvFFC4UfdDz0ajQZCKdrFn+2SbfhJ2dxoewByddut2svDVm2eh108TW/CvwKkNKkkc37uZ7WRLl9k7fOHtq3tg5E72zvGJbKqxaZJPS1TGveyZI9fAuXRwH9aBC5prHoTDpAXHL4os5+0j+2rcUIQGrrQkJXN/pQl6hdqk3L31PpWi6HcrZ4lQzkqI3Bdxr39usgYe8IkSqbjjcIUFjccqKwJysNm4RUDCVGIiDhZ55+Pb02LhQrh/8E2DrR1f6Td/f39oKvdzEHHwuSsrPNWTBklG71iPbm9ED3l030kYoZD9YrIIUguVXPTtNM+42alpoF36aVvZjITpCbDNlzkvfYo7gmWKm7fupfaPow+BAUyOwnD3k=
  on:
    repo: ufal/lindat-common
    all_branches: true
    condition: '-n "$TRAVIS_TAG"'
- provider: script
  script: bash ./ci/push_build.sh
  skip_cleanup: true
  on:
    repo: ufal/lindat-common
    all_branches: true
    condition: '-n "$TRAVIS_TAG" || "$TRAVIS_BRANCH" = "master"'
cache:
  directories:
  - node_modules
  - bower_components
env:
  global:
  - NODE_ENV=travis
  - secure: kviHkRpy/OQSBVYn99OX9xW/sb0wex9P8rJn/VoP1QqbfUNDHttRHG3PG74xLDGLanh7TyrkUni800nbJ1Z4lE7YXt5/JLiDuAhKslzAW1gbignwBQK/LnMdx/+bdpnxkHU93AEmgRI2uuypvnwGFgFpOr11oIY+V+lxI6ewtuXEGeasaynfYbYvVuKR/AAElZeTJJ4myt75CKud6TGOIiLNT2eYD8ra1A+6NdlJgg+AJFkawY0p6x35KkXvDUoLCJI1ORyyAq4mZj0wwD3zoIAFgZvVqEUmdNxqx+km/JsPh9lonr7rFu056NgtGiRV9+OTYxeiAr1nVDGoymIfzPJUuQbjtdQLCvp9jM7fGcElsHy81btz2CTZtU3WXKwVp58/yoOxLXAUR7pX9iFatIoDnPzXDdHgnAVaqKo8tIids6OkGo1vbeItSfwJgvUZkx9pNyD2SKL3iBN5I8A+HgAbM08ghO4ijwahzpvGgd0s+jOmswhGOAfhrGxwiXRm68tBkfFj0Dn+XXoEHgbkOnPf6PnMhfEZhcJ4KCFmRm93Y/noKrq/SBU9/xz0+mWziWfFakYuLh21e0EGr+F2wtEPqFYc1+SmPvK6MdE793+tWjK4to3ukqQRbqZ1UqzrAN2RHDA/S5O67G8tYwMroK5QZfd5bFB6A462jyehKo0=
  - secure: iT1g3ygLZk51UYH9/TAbB6t0gRo4peHqigDqS3W4pSXSACFFSHEzFExK3TosxxNxb556k/yFdR9U6tq0IBwRfie44BEgd4zlxL8ZmEvFbX7GcYKxnZdKvaNkW4BuMqilxZhJ/r32MIkrcSkHj7o8rM8KS/XUsxIrwidTFg9dn9uJbKi0wk3NwirUWih1FbTOBKmdgvCnxCTYI1xICjNMF6Un0iAiBqslc4lj9DeWtgerlRi1iaWG0a32bTy+sS1WK0Tgbn4MANljCNBkuB5HNTcvy7JGtH6BqBFzpX3ZCc0kleNDl1q7kvMadF8jznefRxyBUhJTSOtgCCe0qCxjvBysu7qif1kq/UVGbDGrCxYYKhpZ35r2IG1e5BGKE/7O8rdF1r5GfsYJRjTWl3BowKv1np1DgdPBDofyca4ySavN5qZe8HyC/FteB0tDumBX7i2KO1tiniGY2pAVOr29mVvsTEBznEwrdCxrv6nHKLTsV4JpXOA96ZMx8XYdigun6KCJ4AjDwUL+qHHETIPxNuQeHRjLLJnNlLgngTZ29AfyIpbLSqthykiNh+TEVl6DqxivefCBv163AH57BvTXrSm/enivNpqZCnpvzKILzMTy7axYzIyMkeEhcJp3UXKRnVcZekRW5SDMFq82ki1GQUPmEeExS6kodxMJQNslv9o=
